config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :rooms
    resources :room_types
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :room_type
end

app/models/room_type.rb
class RoomType < ApplicationRecord
  has_many :rooms
end

app/controllers/admin/room_types_controller.rb
class Admin::RoomTypesController < ApplicationController
  before_action :set_room_type, only: [:show, :update, :edit, :destroy]
  def index
    @room_types = RoomType.all
  end

  def new
    @room_type = RoomType.new
  end

  def create
    @room_type = RoomType.new(room_type_params)
     if @room_type.save
       redirect_to admin_room_types_path
     else render :new
     end
  end

  def show

  end
  def destroy
    @room_type.destroy
    redirect_to admin_room_types_path
  end

  def edit

  end
  def update
    if @room_type.update(room_type_params)
      redirect_to admin_room_type_path(@room_type)
    else render :new
    end
  end
  private
    def set_room_type
      @room_type = RoomType.find(params[:id])
    end
    def room_type_params
      params.require(:room_type).permit(:title)
    end
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
     if @room.save
       redirect_to admin_room_path(@room)
     else render :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @room.update(room_params)
      redirect_to admin_room_path
    else render :new
    end
  end

  def destroy
    @room.destroy
    redirect_to admin_rooms_path
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end
    def room_params
      params.require(:room).permit(:room_no, :price, :description, :room_type_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/room_type_helper.rb
module RoomTypeHelper
end

app/views/admin/room_types/edit.html.erb
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Add Room</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 offset-lg-2">
              <%=form_for ([:admin, @room_type]) do |f| %>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Title</label>
                                <%=f.text_field :title, class: "form-control"%>
                            </div>
                        </div>
                    </div>

                    <div class="m-t-20 text-center">
                        <%=f.submit "Save", class: "btn btn-primary submit-btn"%>
                        <%=link_to "Cancel", admin_room_types_path, class: "btn btn-danger submit-btn"%>
                    </div>
                <%end%>
            </div>
        </div>
    </div>

app/views/admin/room_types/index.html.erb
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-4">
                <h4 class="page-title">All Room Types</h4>
            </div>
            <div class="col-sm-8 col-8 text-right m-b-20">
                <%=link_to "Add Room Type", new_admin_room_type_path, class: "btn btn btn-primary btn-rounded float-right "%>
            </div>
        </div>
				<div class="row">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-striped custom-table">
								<thead>
									<tr>
                    <th>Room ID</th>
										<th>Title</th>

										<th class="text-right">Action</th>
									</tr>
								</thead>
								<tbody>
                  <%@room_types.each do |room_type| %>
						      <tr>
                    <td><%=room_type.id%></td>
                    <td><%=room_type.title%></td>

										<td class="text-right">
											<div class="dropdown dropdown-action">
												<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
												<div class="dropdown-menu dropdown-menu-right">
													<i class="fa fa-pencil m-r-5"></i> <%=link_to "edit", edit_admin_room_type_path(room_type), class: "dropdown-item"%>
													<i class="fa fa-trash-o m-r-5"></i><%=link_to "Delete", admin_room_type_path(room_type), class: "dropdown-item", method: :delete, data: {confirm: "Are You Sure!"}%>
												</div>
											</div>
										</td>
									</tr>
                  <%end%>
								</tbody>
							</table>
						</div>
					</div>
        </div>
      </div>
  </div>

app/views/admin/room_types/new.html.erb
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Add Room</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 offset-lg-2">
              <%=form_for ([:admin, @room_type]) do |f| %>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Title</label>
                                <%=f.text_field :title, class: "form-control"%>
                            </div>
                        </div>
                    </div>

                    <div class="m-t-20 text-center">
                        <%=f.submit "Save", class: "btn btn-primary submit-btn"%>
                        <%=link_to "Cancel", admin_room_types_path, class: "btn btn-danger submit-btn"%>
                    </div>
                <%end%>
            </div>
        </div>
    </div>

app/views/admin/room_types/show.html.erb
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-4">
                <h4 class="page-title">All Rooms</h4>
            </div>
            <div class="col-sm-8 col-8 text-right m-b-20">
                <%=link_to "All Room Type", admin_room_types_path, class: "btn btn btn-primary btn-rounded float-right "%>
            </div>
        </div>
				<div class="row">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-striped custom-table">
								<thead>
									<tr>
                    <th>ID</th>
										<th>Title</th>

										<th class="text-right">Action</th>
									</tr>
								</thead>
								<tbody>
						      <tr>
                    <td><%=@room_type.id%></td>
                    <td><%=@room_type.title%></td>
										<td class="text-right">
											<div class="dropdown dropdown-action">
												<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
												<div class="dropdown-menu dropdown-menu-right">
													<a class="dropdown-item" href="edit-room.html"><i class="fa fa-pencil m-r-5"></i> Edit</a>
													<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_room"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
												</div>
											</div>
										</td>
									</tr>

								</tbody>
							</table>
						</div>
					</div>
        </div>
      </div>
  </div>

app/views/admin/rooms/edit.html.erb
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Add Room</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 offset-lg-2">
              <%=form_for ([:admin, @room]) do |f| %>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Room Number</label>
                                <%=f.text_field :room_no, class: "form-control"%>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                              <label>Price</label>
                                <%=f.number_field :price, class: "form-control"%>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Room type</label>
                                <input class="form-control" type="text">
                            </div>

                        </div>
                    </div>

                    <div class="form-group">
                        <label>Description</label>
                        <%=f.text_area :description, class: "form-control"%>

                    </div>

                    <div class="m-t-20 text-center">
                        <%=f.submit "Update", class: "btn btn-primary submit-btn"%>
                        <%=link_to "Cancel", admin_rooms_path, class: "btn btn-danger submit-btn"%>
                    </div>
                <%end%>
            </div>
        </div>
    </div>

app/views/admin/rooms/index.html.erb
<!-- Add Navbar Here --!>
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-4">
                <h4 class="page-title">All Rooms</h4>
            </div>
            <div class="col-sm-8 col-8 text-right m-b-20">
              <%=link_to "Add Room", new_admin_room_path, class: "fa fa-plus btn btn btn-primary btn-rounded float-right "%>
            </div>
        </div>
				<div class="row">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-striped custom-table">
								<thead>
									<tr>
                    <th>Room ID</th>
										<th>Room number</th>
										<th>Price</th>
                    <th>Room type</th>
										<th class="text-right">Action</th>
									</tr>
								</thead>
								<tbody>
                  <%@rooms.each do |room| %>
						      <tr>
                    <td><%=room.id%></td>
                    <td><%=room.room_no%></td>
										<td><%=number_to_currency(room.price)%></td>
										<td><%=room.room_type.title%></td>
										<td class="text-right">
											<div class="dropdown dropdown-action">
												<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
												<div class="dropdown-menu dropdown-menu-right">
													<%=link_to "edit", edit_admin_room_path(room), class: "dropdown-item fa fa-pencil m-r-5 "%>
													<%=link_to "Delete", admin_room_path(room), class: "fa fa-trash-o m-r-5 dropdown-item", method: :delete, data: {confirm: "Are You Sure!"}%>
												</div>
											</div>
										</td>
									</tr>
                  <%end%>
								</tbody>
							</table>
						</div>
					</div>
        </div>
      </div>
  </div>

<!--Add Footer Here--!>

app/views/admin/rooms/new.html.erb
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <h4 class="page-title">Add Room</h4>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 offset-lg-2">
              <%=form_for ([:admin, @room]) do |f| %>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Room Number</label>
                                <%=f.text_field :room_no, class: "form-control"%>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                              <label>Price</label>
                                <%=f.number_field :price, class: "form-control"%>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Room type</label>
                                <%=f.collection_select :room_type_id, RoomType.all, :id, :title, {}, class: "select form-control"%>

                            </div>

                        </div>
                    </div>

                    <div class="form-group">
                        <label>Description</label>
                        <%=f.text_area :description, class: "form-control"%>

                    </div>

                    <div class="m-t-20 text-center">
                        <%=f.submit "Save", class: "btn btn-primary submit-btn"%>
                        <%=link_to "Cancel", admin_rooms_path(@room), class: "btn btn-danger submit-btn"%>
                    </div>
                <%end%>
            </div>
        </div>
    </div>

app/views/admin/rooms/show.html.erb
<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-4">
                <h4 class="page-title">All Rooms</h4>
            </div>
            <div class="col-sm-8 col-8 text-right m-b-20">
                <%=link_to "All Room", admin_rooms_path, class: "btn btn btn-primary btn-rounded float-right "%>
            </div>
        </div>
				<div class="row">
					<div class="col-md-12">
						<div class="table-responsive">
							<table class="table table-striped custom-table">
								<thead>
									<tr>
                    <th>Room ID</th>
										<th>Room number</th>
										<th>Price</th>
                    <th>Room type</th>
										<th class="text-right">Action</th>
									</tr>
								</thead>
								<tbody>

						      <tr>
                    <td><%=@room.id%></td>
                    <td><%=@room.room_no%></td>
										<td><%=number_to_currency (@room.price)%></td>
										<td><%=@room.room_type.title%></td>
										<td class="text-right">
											<div class="dropdown dropdown-action">
												<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
												<div class="dropdown-menu dropdown-menu-right">
													<a class="dropdown-item" href="edit-room.html"><i class="fa fa-pencil m-r-5"></i> Edit</a>
													<a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete_room"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
												</div>
											</div>
										</td>
									</tr>

								</tbody>
							</table>
						</div>
					</div>
        </div>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelBookingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%=render "Shared/NavBar"%>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>